### ISSUE TITLE
Add button class

### ISSUE THREAD

**Issue by SlateLH** [xtnc/xtnc-ui#1]
### Description
Create a class to be used for button elements with tailwindcss styles.

### Acceptance Criteria
A button class that can be applied to HTML button tags is made an available style.

### Tasks
- [ ] Basic button class
- [ ] Colored buttons
- [ ] Outlined/filled buttons
- [ ] Small/medium/large button sizes
